//! Build script for ootmm crate
//!
//! This script embeds static data files (YAML world definitions) into the binary
//! at compile time, generating accessor functions for runtime access.

use std::env;
use std::fs::{self, File};
use std::io::{BufWriter, Write};
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("embedded_data.rs");

    let mut file = BufWriter::new(File::create(&dest_path).expect("Failed to create output file"));

    // Write module header (use regular comments since this is included)
    writeln!(file, "// Auto-generated embedded data module").unwrap();
    writeln!(file, "// DO NOT EDIT - Generated by build.rs").unwrap();
    writeln!(file).unwrap();

    // Collect all world YAML files
    let data_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("data");
    let world_dir = data_dir.join("world");

    let mut world_files = Vec::new();

    if world_dir.exists() {
        println!("cargo:rerun-if-changed={}", world_dir.display());

        for entry in fs::read_dir(&world_dir).expect("Failed to read world directory") {
            let entry = entry.expect("Failed to read directory entry");
            let path = entry.path();

            if let Some(ext) = path.extension() {
                if ext == "yaml" || ext == "yml" {
                    let file_name = path
                        .file_stem()
                        .expect("No file stem")
                        .to_string_lossy()
                        .to_string();

                    // Notify cargo to rerun if this file changes
                    println!("cargo:rerun-if-changed={}", path.display());

                    world_files.push((file_name, path));
                }
            }
        }
    }

    // Sort for deterministic output
    world_files.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate embedded data constants
    writeln!(file, "/// Embedded world data files").unwrap();
    writeln!(file, "pub mod world {{").unwrap();

    for (name, path) in &world_files {
        let const_name = name.to_uppercase().replace('-', "_");
        let rel_path = path
            .strip_prefix(env!("CARGO_MANIFEST_DIR"))
            .unwrap_or(path);

        // Convert path to forward slashes for cross-platform compatibility
        // Windows paths with backslashes don't work in include_str! macros
        let rel_path_str = rel_path
            .to_string_lossy()
            .replace('\\', "/");

        writeln!(file, "    /// World data from `{}`", rel_path_str).unwrap();
        writeln!(
            file,
            "    pub const {}: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\"));",
            const_name,
            rel_path_str
        )
        .unwrap();
        writeln!(file).unwrap();
    }

    // Generate a list of all world files
    writeln!(
        file,
        "    /// Returns all embedded world data files as (name, content) pairs"
    )
    .unwrap();
    writeln!(file, "    #[must_use]").unwrap();
    writeln!(
        file,
        "    pub fn all() -> &'static [(&'static str, &'static str)] {{"
    )
    .unwrap();
    writeln!(file, "        &[").unwrap();
    for (name, _) in &world_files {
        let const_name = name.to_uppercase().replace('-', "_");
        writeln!(file, "            (\"{}\", {}),", name, const_name).unwrap();
    }
    writeln!(file, "        ]").unwrap();
    writeln!(file, "    }}").unwrap();

    writeln!(file, "}}").unwrap();
    writeln!(file).unwrap();

    // Generate a function to get world data by name
    writeln!(
        file,
        "/// Returns embedded world data by file name (without extension)."
    )
    .unwrap();
    writeln!(file, "///").unwrap();
    writeln!(file, "/// # Arguments").unwrap();
    writeln!(
        file,
        "/// * `name` - The name of the world file (e.g., \"oot_kokiri\")"
    )
    .unwrap();
    writeln!(file, "///").unwrap();
    writeln!(file, "/// # Returns").unwrap();
    writeln!(
        file,
        "/// The YAML content of the world file, or `None` if not found."
    )
    .unwrap();
    writeln!(file, "#[must_use]").unwrap();
    writeln!(
        file,
        "pub fn get_world_data(name: &str) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(file, "    match name {{").unwrap();
    for (name, _) in &world_files {
        let const_name = name.to_uppercase().replace('-', "_");
        writeln!(file, "        \"{}\" => Some(world::{}),", name, const_name).unwrap();
    }
    writeln!(file, "        _ => None,").unwrap();
    writeln!(file, "    }}").unwrap();
    writeln!(file, "}}").unwrap();
    writeln!(file).unwrap();

    // Generate summary info
    writeln!(file, "/// Returns the number of embedded world files.").unwrap();
    writeln!(file, "#[must_use]").unwrap();
    writeln!(file, "pub const fn world_file_count() -> usize {{").unwrap();
    writeln!(file, "    {}", world_files.len()).unwrap();
    writeln!(file, "}}").unwrap();

    file.flush().expect("Failed to flush output file");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data");
}
