//! Build script for the ootmm crate.
//!
//! This script reads YAML world data files and generates Rust code that embeds
//! them into the binary at compile time.

use std::env;
use std::fs::{self, File};
use std::io::{BufWriter, Write};
use std::path::Path;

fn main() {
    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("embedded_world_data.rs");
    let manifest_dir = env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let data_dir = Path::new(&manifest_dir).join("data");

    let mut file = BufWriter::new(File::create(&dest_path).expect("Failed to create output file"));

    // Collect all YAML files from both oot and mm directories
    let mut oot_files = Vec::new();
    let mut mm_files = Vec::new();

    let oot_dir = data_dir.join("oot");
    let mm_dir = data_dir.join("mm");

    if oot_dir.exists() {
        collect_yaml_files(&oot_dir, &mut oot_files);
    }

    if mm_dir.exists() {
        collect_yaml_files(&mm_dir, &mut mm_files);
    }

    // Sort for deterministic output
    oot_files.sort();
    mm_files.sort();

    // Generate the embedded data module
    writeln!(file, "// Auto-generated embedded world data.").unwrap();
    writeln!(file, "// This module is generated by build.rs and contains YAML world data").unwrap();
    writeln!(file, "// embedded at compile time.").unwrap();
    writeln!(file).unwrap();

    // Generate OoT data array
    writeln!(file, "/// Embedded YAML data for Ocarina of Time regions.").unwrap();
    writeln!(file, "pub static OOT_WORLD_DATA: &[(&str, &str)] = &[").unwrap();
    for yaml_path in &oot_files {
        let relative = yaml_path.strip_prefix(&data_dir).unwrap();
        let name = relative.display().to_string().replace('\\', "/");
        writeln!(
            file,
            "    (\"{}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/data/{}\"))),",
            name, name
        )
        .unwrap();
        // Tell Cargo to rerun if this file changes
        println!("cargo::rerun-if-changed={}", yaml_path.display());
    }
    writeln!(file, "];").unwrap();
    writeln!(file).unwrap();

    // Generate MM data array
    writeln!(file, "/// Embedded YAML data for Majora's Mask regions.").unwrap();
    writeln!(file, "pub static MM_WORLD_DATA: &[(&str, &str)] = &[").unwrap();
    for yaml_path in &mm_files {
        let relative = yaml_path.strip_prefix(&data_dir).unwrap();
        let name = relative.display().to_string().replace('\\', "/");
        writeln!(
            file,
            "    (\"{}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/data/{}\"))),",
            name, name
        )
        .unwrap();
        // Tell Cargo to rerun if this file changes
        println!("cargo::rerun-if-changed={}", yaml_path.display());
    }
    writeln!(file, "];").unwrap();
    writeln!(file).unwrap();

    // Generate combined data array
    writeln!(file, "/// All embedded YAML world data (both OoT and MM).").unwrap();
    writeln!(file, "pub static ALL_WORLD_DATA: &[(&str, &str)] = &[").unwrap();
    for yaml_path in oot_files.iter().chain(mm_files.iter()) {
        let relative = yaml_path.strip_prefix(&data_dir).unwrap();
        let name = relative.display().to_string().replace('\\', "/");
        writeln!(
            file,
            "    (\"{}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/data/{}\"))),",
            name, name
        )
        .unwrap();
    }
    writeln!(file, "];").unwrap();

    // Tell Cargo to rerun if the data directories change
    println!("cargo::rerun-if-changed={}", data_dir.display());
    println!("cargo::rerun-if-changed={}", oot_dir.display());
    println!("cargo::rerun-if-changed={}", mm_dir.display());
}

/// Recursively collect all YAML files in a directory.
fn collect_yaml_files(dir: &Path, files: &mut Vec<std::path::PathBuf>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_yaml_files(&path, files);
            } else if let Some(ext) = path.extension() {
                if ext == "yaml" || ext == "yml" {
                    files.push(path);
                }
            }
        }
    }
}
